Vagrant.configure("2") do |config|

  config.env.enable

  # Workaround for Vagrant issue with TTY errors - copied from
  # https://superuser.com/questions/1160025/how-to-solve-ttyname-failed-inappropriate-ioctl-for-device-in-vagrant
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.define "vm" do |vm|
    vm.vm.box = ENV['BOXNAME']
    vm.vm.provider "virtualbox" do |v|
      v.memory = ENV['MEMORY']
      # Synchronize clock in one step if difference is more than 1000 ms / 1s
      # Copied from https://stackoverflow.com/questions/19490652/how-to-sync-time-on-host-wake-up-within-virtualbox
      v.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
    end
    vm.vm.provision "file", source: "local-repo.env", destination: "/tmp/local-repo.env"
    vm.vm.provision "file", source: "../offline-install/offline_repo.tar.gz", destination: "/tmp/offline_repo.tar.gz"
    vm.vm.provision :shell, :path => 'remove-regular-repos.sh'
    vm.vm.provision :shell, :path => '../offline-install/install-offline.sh', :args => "/tmp/offline_repo.tar.gz"
  end

end
